spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #druid
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 100
    minIdle: 500
    maxActive: 1000
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  #redis
  redis:
    host: 134.175.26.115
    port: 6379
    password: pidao123
    jedis:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500
    timeout: 0
 #rabbitMq
  rabbitmq:
    host: 134.175.26.115
    port: 5672
    username: guest
    password: guest


#mybatis
mybatis:
  type-aliases-package: com.pi.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.pi.miaosha.dao/*.xml





